### ISSUE TITLE
Can not download file on Android with Firefox

### ISSUE THREAD

**Issue by shalva97** [Feuerhamster/web-youtube-downloader#3]
So when I select the file variant I want to download I get redirected to it instead of showing download dialog ![Screenshot_20220831-003811_Firefox.png](https://user-images.githubusercontent.com/22417494/187538570-5cd152c7-d3f0-413a-a850-abf7917430c8.png)

**Comment by Feuerhamster** [comment]
This software only redirects you to the source file on the Google servers. You have to download it yourself. Normally, every browser provides a download button when directly open a file on the web. 
So I have no control over what happens after you got redirected to a file. 

This means this is not a problem with this software.
